server:
  session-timeout: 1800
  servlet:
    session:
      timeout: 1800
  port: 8084
spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  cache:
    type: ehcache
    #    spring缓存配置，需在启动类前加上@EnableCaching
    ehcache:
      config: classpath:config/ehcache.xml
#[弃用]配置缓存和session存储方式，默认ehcache,可选redis,[弃用]调整至 spring cache type【shiro.用户，权限，session，spring.cache通用】
#[弃用]cacheType: ehcache